### ISSUE TITLE
add version to output

### ISSUE THREAD

**Issue by StephanHCB** [StephanHCB/go-generator-cli#3]

**Comment by Avataw** [comment]
Can you provide some additional input? I might actually work on this :)

**Comment by StephanHCB** [comment]
> Can you provide some additional input? I might actually work on this :)

Certainly, I'd be happy to take a contribution here.

The go compiler allows setting the value of a variable via command line flags to `go build`. see https://stackoverflow.com/questions/47509272/how-to-set-package-variable-using-ldflags-x-in-golang-build

Since go-generator-cli is downloaded as a single binary, and usually named just `go-generator-cli`, it is not obvious which version you have installed. That's why I'd like the program to log its release version, maybe right in the first line "welcome to go-generator-cli v1.4.1".

This involves some change to the build actions so that the release version is passed into the go build. Not sure if the go-semantic-release action supports this directly.
